export const FETCH_MANAGE_RENT_HOUSE_REQUEST = 'FETCH_MANAGE_RENT_HOUSE_REQUEST'
export const FETCH_MANAGE_RENT_HOUSE_SUCCESS = 'FETCH_MANAGE_RENT_HOUSE_SUCCESS'
export const FETCH_MANAGE_RENT_HOUSE_FAILURE = 'FETCH_MANAGE_RENT_HOUSE_FAILURE'


